version: "3.8"
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: onboarding
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d

  customer-service:
    build: ./customer-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/onboarding
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  insurance-service:
    build: ./insurance-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/onboarding
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CUSTOMER_SERVICE_URL: http://customer-service:8080
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - customer-service

volumes:
  pgdata:

